blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :articles do
    resources :comments
    resources :votes, only: [:create, :destroy, :update]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :favourites, only: [:create, :destroy]

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  #this uses teh ImageUploader class to the upload an image for this model
  # we  must have a field called "image" for this model
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  def vote_for(user)
    votes.find_by_user_id(user)
  end


    def liked_by?(user)
    # likes will give all the likes objects to the current question record
    # it's the same as calling `self.likes`
    # we filter those likes by a spacific by simply passing the user: user
    # option in the where function
    # the present? will give true if there is at least one element returned
    # and will return false if there are no elements
    likes.where(user: user).present?
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  def favourite_for(user)
    favourites.find_by_user_id(user)
  end


end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  # I haven't added these defs in order.

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
    @like = @article.like_for(current_user)
    @vote = @article.vote_for(current_user)
    @favourite = @article.favourite_for(current_user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
     # Check if article is saved
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
  end

  # Allow user to update articles
  def update
   @article = Article.find(params[:id])

   if @article.update(article_params)
     redirect_to @article
   else
     render 'edit'
   end
  end

  #Allow user to delete articles
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  # Prevent users from accessing this method
  def article_params
    params.require(:article).permit(:title, :image, :text, {tag_ids: []})

  end

  def find_article
    @article = Article.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :image, :email, :password, :password_confirmation)
  end



end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for :article, url: articles_path, multiport: true do |f| %>
<!-- Check if there are any errors in the blog post and title (did the user do anything illegal like write a 2-character title) -->

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :tag_ids %>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name  %>
  </p>
  <p>Attach an image:
      <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit "Submit Blog Post", class: "btn btn-primary" %>
  </p>
</div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>


<% end %>

blog/app/views/articles/show.html.erb
<div class="col-md-8">

<% if @article.image.present? %>
<%= image_tag article.image.url(:thumb) %>
<% end %>

  <div class="col-md-4">
    <%= image_tag @article.image.url %>
  </div>

  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>

  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <div class="votes">


  <h3>Vote!</h3>

  <% if @vote.nil? %>
      <%= link_to "<i class='glyphicon glyphicon-triangle-top voting'></i>".html_safe,
                    article_votes_path(@article, {vote: {is_up: true}}), method: :post %>
      <br>
      <%= link_to "<i class='glyphicon glyphicon-triangle-bottom voting'></i>".html_safe,
                    article_votes_path(@article, {vote: {is_up: false}}), method: :post %>
    <% elsif @vote.is_up? %>
      <%= link_to "<i class='glyphicon glyphicon-triangle-top voting vote-active'></i>".html_safe,
                    article_vote_path(@article, @vote), method: :delete %>
      <br>
      <%= link_to "<i class='glyphicon glyphicon-triangle-bottom voting'></i>".html_safe,
                  article_vote_path(@article, @vote, {vote: {is_up: false}}), method: :patch %>
    <% else %>
      <%= link_to "<i class='glyphicon glyphicon-triangle-top voting'></i>".html_safe,
                    article_vote_path(@article, @vote, {vote: {is_up: true}}), method: :patch %>
      <br>
      <%= link_to "<i class='glyphicon glyphicon-triangle-bottom voting vote-active'></i>".html_safe,
                    article_vote_path(@article, @vote), method: :delete %>
    <% end %>
  </div>

  <hr>


  <p>Liked <%= @article.likes.count %> times</p>

  <% if @article.liked_by?(current_user) %>
    <%= link_to "Un-Like", article_like_path(@article, @like), method: :delete %>
  <% else %>

    <%= link_to "Like", article_likes_path(@article), method: :post %>
  <% end %>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>

  <% if @article.favourited_by?(current_user) %>
    <%= link_to "Un-Favourite", article_favourite_path(@article, @favourite),
                method: :delete  %>
  <% else %>
    <%= link_to "Favourite", article_favourites_path(@article), method: :post %>
  <% end %>


</div>