code_snippets/codesnipper/config/routes.rb
Rails.application.routes.draw do
#  get 'welcome/index'

  root 'categories#index'

  resources :categories
  resources :snippets


end

code_snippets/codesnipper/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :snippets
  #has_many :answers, dependent: :destroy

end

code_snippets/codesnipper/app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: {message: "must be provided"},
                    uniqueness: true,
                    length: {minimum: 5}
  #validates :code, uniqueness: {scope: :title}
  def self.search(query,category)
    if(category.to_i > 0)
         where(["category_id LIKE ? AND
                (title LIKE ? OR code LIKE ?)", 
                "#{category}",
                "%#{query}%",
                "%#{query}%"])
    else
         where(["title LIKE ? OR code LIKE ?", 
                "%#{query}%",
                "%#{query}%"])
    end
  end 

end

code_snippets/codesnipper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  ## To do: get code syntax working
	class CodeRayify < Redcarpet::Render::HTML
	  def block_code(code)
	    #CodeRay.scan(code, language).div
      #CodeRay.scan(code, :ruby).div(:line_numbers => :table)
      CodeRay.scan(code, :ruby).div(:line_numbers => :table)
	  end
	end

	def markdown(text)
	  coderayified = CodeRayify.new(:filter_html => true,
	                                :hard_wrap => true)
	  options = {
	    :fenced_code_blocks => true,
	    :no_intra_emphasis => true,
	    :autolink => true,
	    :lax_html_blocks => true,
	  }
	  markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
	  markdown_to_html.render(text).html_safe
	end

  def listcategory
    c = Category.all
  end

  helper_method :markdown, :listcategory

end

code_snippets/codesnipper/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   def index
     @categories = Category.all
   end

   def show
    @category = Category.find params[:id] 
   end

end

code_snippets/codesnipper/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, except: [:index, :new, :create]
  def index
    #@snippets = Snippet.all
    if (params[:search] && params[:category_id])
      @snippets = Snippet.search(params[:search], params[:category_id])
    else
      @snippets = Snippet.all.page(params[:page])
    end
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      redirect_to snippet_path(@snippet)
    else
      render :new
    end
    
  end

  def edit

  end

  def show

  end

  def update
    if @snippet.update(snippet_params) 
      redirect_to snippet_path(@snippet)
    else
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to snippets_path
  end

  private

  def snippet_params
       params.require(:snippet).permit([:title, :code, :category_id])
  end

  def find_snippet
    @snippet = Snippet.find params[:id]
  end

end

code_snippets/codesnipper/app/helpers/snippets_helper.rb
module SnippetsHelper
end

code_snippets/codesnipper/app/views/categories/index.html.erb
<h2>Snippet Languages</h2>
<ul>
<% @categories.each do |category| %>
  <li><%=link_to "#{category.name} | #{category.snippets.count} snipppets", category_path(category) %></li>
<% end %>
</ul>

code_snippets/codesnipper/app/views/categories/show.html.erb
<h1><%=@category.name %></h1>

<% @category.snippets.each do |snippet| %>
  <%= link_to snippet.title, snippet_path(snippet)%><br>
<% end %>

code_snippets/codesnipper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codesnipper</title>

  <link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav>
  <div class="logo">
    <%= image_tag("codelogo.png") %>
  </div>
  <div class="view-library">
    <p>
      <p>View Our Full Library of Snippets:</p>
      <% listcategory.each do |category| %>
      <%= link_to "#{category.name}", category_path(category)  %>
      <% end %>
    </p>
  </div>

<div class="search">
  <%= form_tag(snippets_path, :method => "get") do %>
      <div>
        <%= text_field_tag :search, params[:search], placeholder: "Search for a snippet" %>
        <% all_options = '<option value="0">All</option>'.html_safe %>
        <%= select_tag :category_id,
          all_options+options_from_collection_for_select(Category.all,
                                                         :id, :name,
                                                         params[:category_id])%>
        <button type="submit">Search</button>
      </div>
  <% end %>


</div>
<br>
<br>
<div class="create-all-home">
    <%= link_to "Create Snippet", new_snippet_path %> |
    <%= link_to "All Snippets", snippets_path %> |
    <%= link_to "Languages", root_path %>
</div>

  </nav>
<hr>


<%= yield %>

</body>
</html>

code_snippets/codesnipper/app/views/snippets/_form.html.erb
<% if @snippet.errors.any? %>
    <ul>
    <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# form_for :snippet, url: snippet_path(@snippet), method: :patch do |f| %>
<%= form_for @snippet do |f| %>

<table>
  <tr>
    <th>
      <%= f.label :category %>
    </th>
    <th>
      <%= f.label :title %>
    </th>
    <th>
      <%= f.label :code %>
    </th>
  </tr>

  <tr>
    <td><%= f.collection_select :category_id, Category.all, :id, :name %></td>
    <td><%= f.text_field :title %></td>
    <td><%= f.text_area :code %></td>
    <td><%= f.submit 'Save' %></td>
  </tr>
</table>
</tr>
<% end %>

code_snippets/codesnipper/app/views/snippets/edit.html.erb
<h1> Edit Snippet </h1>
  <%= render 'form' %>
  <%= link_to 'Edit', edit_snippet_path(@snippet) %>
  <%= link_to 'Delete', snippet_path, method: :delete, data: {confirm: 'Are you sure?'}  %>

code_snippets/codesnipper/app/views/snippets/index.html.erb
<h2>All Snippets</h2>
<br>
<% @snippets.each do |snippet| %>
  <%= link_to snippet.title, snippet_path(snippet) %><br>
<% end %>

code_snippets/codesnipper/app/views/snippets/new.html.erb
<h2> Add Snippet </h2>
<%= render 'form' %>

code_snippets/codesnipper/app/views/snippets/show.erb
<h2>Your <%= @snippet.category.name %> Snippet</h2>
<br>
<div class="snippet-title">
  <%= @snippet.title %>
</div>
<div class="code">
  <%= markdown(@snippet.code) %>
</div>
<br>
<%= link_to 'Edit Snippet', edit_snippet_path(@snippet) %> |
<%= link_to 'Delete Snippet', snippet_path, method: :delete %>